[[news]]
date = "2025-12"
content = "🎉🎉 1 paper accepted by ***<font color="#A52A2A">Engineering Applications of Artificial Intelligence</font>"

[[news]]
date = "2025-10"
content = "🎉🎉 1 paper accepted by ***<font color="#A52A2A">Scientific Reports</font>"
