[[news]]
date = "2025-12"
content = "🏆 获评国防科技大学校优秀奖学金！"

[[news]]
date = "2025-12"
content = "🎉🎉 论文被 Engineering Applications of Artificial Intelligence 接收！"

[[news]]
date = "2025-10"
content = "🎉🎉 论文被 Scientific Reports 接收！"
